[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit SSD1306@^2.5.8
  adafruit/Adafruit GFX Library@^1.11.4

build_flags =
  -DSSD1306_128_64
  -DARDUINO=10805
